export enum ActionTypes {
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  SET_ACTIVE_CARD_COUNT = "SET_ACTIVE_CARD_COUNT",
  SET_CANCELED_CARD_COUNT = "SET_CANCELED_CARD_COUNT",
  SET_TOTAL_CARD_VALUE = "SET_TOTAL_CARD_VALUE",
  INIT_CARDS = "INIT_CARDS",
  ADD_CARD = "ADD_CARD",
  TOGGLE_CARD_STATUS = "TOGGLE_CARD_STATUS",
}
