export enum ActionTypes {
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  SET_ACTIVE_CARD_COUNT = "SET_ACTIVE_CARD_COUNT",
  SET_CANCELED_CARD_COUNT = "SET_CANCELED_CARD_COUNT",
  SET_TOTAL_CARD_VALUE = "SET_TOTAL_CARD_VALUE",
}
